"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import datetime
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%6oy(c1ec(1tw5f1q!(jn*&7%=nw6i&+-k=tw8#@s_@#9*f-pr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'import_export',
    
    'api.apps.ApiConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'main/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'api_douanes',
        'USER': 'postgres',
        'PASSWORD': '7895123',
        'HOST': 'localhost'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR , 'static')
STATIC_URL = '/static/'
STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main/static')
]

# Media folder settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "api.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    'JWT_AUTH': {
        'JWT_EXPIRATION_DELTA': datetime.timedelta(minutes=30),  # Access token expiration time
        'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),  # Refresh token expiration time
    },
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly"
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ["Bearer"],
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(seconds=30), # minutes=5
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(minutes=1), # days=1
}

# DOUANES (PRODUCTION)
DOUANES_USER = "cntsid01"
DOUANES_PASSWORD = "Dou@n3Micro!mprot2025"
DOUANES_LOGIN_DOUANES = "http://10.200.1.18:8085/auth/login"
DOUANES_POST_DATA_CURRENCY = "http://10.200.1.18:8085/api/douane/devise"
DOUANES_POST_DATA_GOODS = "http://10.200.1.18:8085/api/douane/marchandise"


DOUANES_USER_TEST = "douanes"
DOUANES_PASSWORD_TEST = "U*Nr{7hJR31jW@"
DOUANES_LOGIN_DOUANES_TEST = "http://127.0.0.1:8001/api/auth/"
DOUANES_POST_DATA_CURRENCY_TEST_SUCCESS = "http://127.0.0.1:8001/api/currency/test-success/"
DOUANES_POST_DATA_CURRENCY_TEST_ERROR = "http://127.0.0.1:8001/api/currency/test-error/"
DOUANES_POST_DATA_GOODS_TEST_SUCCESS = "http://127.0.0.1:8001/api/goods/test-success/"
DOUANES_POST_DATA_GOODS_TEST_ERROR = "http://127.0.0.1:8001/api/goods/test-error/"

# LOCAL DOUANES - ANAE
ANAE_DOUANES_USER = '9poXzUq1849YNfbP'
ANAE_DOUANES_PASSWORD = 'Q£?^Ixo3[*1}=>6'
ANAE_LOGIN_DOUANES = "http://127.0.0.1:8002/api/auth/" 
LOCAL_API_DOUANES_PUT_DATA_CURRENCY = "http://127.0.0.1:8002/api/micro-importer/update-currency/"
LOCAL_API_DOUANES_PUT_DATA_GOODS = "http://127.0.0.1:8002/api/micro-importer/update-marchandise/"
LOCAL_API_DOUANES_PUT_DATA_GOODS_ITEM = "http://10.200.1.18:8085/api/micro-importer/update-goods-item/"

APPEND_SLASH=False

### douanes
### U*Nr{7hJR31jW@


